### ISSUE TITLE
Segmentation fault when running WASM

### ISSUE THREAD

**Issue by hoangpq** [SkylerLipthay/mini-v8#2]
I created simple code follow the v8 example [hello_world.cc](https://github.com/v8/v8/blob/master/samples/hello-world.cc) to run WASM

- Platform: MacOS
- Ruby gem: libv8-7.3.492.27.1-universal-darwin-18

```rust
fn main() {
    let mv8 = MiniV8::new();
    let value: Value = mv8
        .eval(
            r#"
              let bytes = new Uint8Array([
                0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x07, 0x01,
                0x60, 0x02, 0x7f, 0x7f, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x00, 0x07,
                0x07, 0x01, 0x03, 0x61, 0x64, 0x64, 0x00, 0x00, 0x0a, 0x09, 0x01,
                0x07, 0x00, 0x20, 0x00, 0x20, 0x01, 0x6a, 0x0b
              ]);

              let module = new WebAssembly.Module(bytes);
              let instance = new WebAssembly.Instance(module);
              instance.exports.add(3, 4)
            "#,
        )
        .unwrap();

    dbg!(value);
}
```

The messages are as follows:
```
[examples/simple.rs:35] value = 7
Segmentation fault: 11
```
@SkylerLipthay Can you help me to point out the issue.

**Comment by SkylerLipthay** [comment]
Thanks for the report! I finally got around to fixing this. Previous releases of MiniV8 had a major memory management flaw in the FFI. This has been fixed, a regression test has been added, and a new MiniV8 release will be published very soon.
