### ISSUE TITLE
Update to latest of v8 crate please

### ISSUE THREAD

**Issue by u9g** [SkylerLipthay/mini-v8#6]
Hi, this is a great package that is a pleasure to work with, I am just hoping that it can be upgraded to latest of the v8 crate and published to cargo with that.

In my experience (of just upgrading the number) it should be a painless upgrade with no code changes.

The reason being is that v8-0.61.0 has a check that fails:

```
error[E0080]: evaluation of constant value failed
    --> /home/u9g/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.61.0/src/isolate.rs:1724:3
     |
1724 |   assert!(size_of::<TypeId>() == size_of::<u64>());
     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: size_of::<TypeId>() == size_of::<u64>()', /home/u9g/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.61.0/src/isolate.rs:1724:3
     |
     = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
```

When on rust 1.72:

```
rustc --version
rustc 1.72.0 (5680fa18f 2023-08-23)
```

**Comment by SkylerLipthay** [comment]
Hi, thanks for the kind words and the notice.

Did something change with `TypeId` in a recent Rust version? I haven't been keeping up. Oh well, no problem. I've just published [0.4.1](https://crates.io/crates/mini-v8/0.4.1) which uses the latest `v8` version.
